spring:
  application:
    name: spellchecker
    

# -- custom port
server.port: 5612
# -- enable compression 
#server.tomcat.compression=4096
#server.tomcat.compressableMimeTypes=application/json,application/xml,text/html,text/plain

logging:
  level:
    com.glosbe: DEBUG
    io.micrometer.influx.InfluxMeterRegistry: WARN


spellchecker.hunspell.dir: /var/hunspell

management:
  metrics:   
    use-global-registry: false 
    web:
      server:
        auto-time-requests: false
    export:
      influx:
        auto-create-db: true # Whether to create the Influx database if it does not exist before attempting to publish metrics to it. (Default: true)
        batch-size: 10000 # Number of measurements per request to use for this backend. If more measurements are found, then multiple requests will be made. (Default: 10000)
        compressed: true # Whether to enable GZIP compression of metrics batches published to Influx. (Default: true)
        connect-timeout: 1s # Connection timeout for requests to this backend. (Default: 1s)
        consistency: one # Write consistency for each point. (Default: one)
        db: collectd # Tag that will be mapped to "host" when shipping metrics to Influx. (Defaut: mydb)
        enabled: true # Whether exporting of metrics to this backend is enabled. (Default: true)
        num-threads: 2 # Number of threads to use with the metrics publishing scheduler. (Default: 2)
        password: mysecret # Login password of the Influx server.
        read-timeout: 10s # Read timeout for requests to this backend. (Default: 10s)
#        retention-policy: my_rp # Retention policy to use (Influx writes to the DEFAULT retention policy if one is not specified).
        step: 30s # Step size (i.e. reporting frequency) to use. (Default: 1m)
        uri: http://host9.glosbe.com:8086 # URI of the Influx server. (Default: http://localhost:8086)
        user-name: myusername # Login user of the Influx server.
